name: Generate and deploy docs
on:
  push:	
    branches:	
      - develop
      - master
jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Generate docs
      run: |
        pip install sphinx django
        python setup.py install
        cd doc
        make html 
    - name: Deploy docs
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: doc/build/html